import { DataNode, FileReader, FinishCallback, ProgressCallback, ErrorCallback } from "./driver";
import { ReportParser, ReportTree, reportNumber, rounding, loadReport, describeReport } from "./report";

class AreaParser implements ReportParser {
    recognized = false;
    // DCのtotalは階層全体、他の3列は各行のlocal areaを表す。
    private tree_ = new ReportTree(4, [false, true, true, true]);
    private root_ = "";
    private pending_ = "";
    private heading_ = false;
    private table_ = false;
    private ended_ = false;

    read(line: string) {
        if (/Generated by:.*Genus|^\s*PDB Frame|"creator"\s*:\s*"Yosys/.test(line)) throw new Error("Not a DC area report.");
        const text = line.trim();
        // 製品バナーのない別形式も、数値行を旧形式として取り込む前に除外する。
        const columns = text.split(/\s+/);
        if (/^Instance\s+Module\b/.test(text) || (columns.includes("Cells") && columns.includes("Instance"))) {
            throw new Error("Not a DC area report.");
        }
        if (/^Hierarchical area distribution/.test(text)) this.recognized = true;
        if (/^Hierarchical cell\s+Absolute/.test(text)) { this.heading_ = true; return; }
        if (!text || /^-[-\s]+$/.test(text)) {
            if (this.root_) this.ended_ = true;
            else if (this.heading_) this.table_ = true;
            return;
        }
        if (this.ended_) return;
        if (!this.table_ && this.recognized) return;
        const candidate = this.pending_ ? `${this.pending_} ${text}` : text;
        const words = candidate.split(/\s+/);
        const numeric = words.length === 7 && !/^\d/.test(words[0]) && words.slice(1, 6).every(word => /^(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(word));
        if (!numeric) {
            if (this.table_) {
                if (!this.pending_ && words.length === 1) { this.pending_ = text; return; }
                throw new Error("Invalid DC area row.");
            }
            return;
        }
        this.recognized = true;
        this.table_ = true;
        this.pending_ = "";
        const data = [1, 3, 4, 5].map(i => reportNumber(words[i], "area"));
        const tolerance = [1, 3, 4, 5].map(i => rounding(words[i]));
        const path = this.root_ ? [this.root_, ...words[0].split("/")] : [words[0]];
        if (!this.root_) this.root_ = words[0];
        this.tree_.add(path, data, tolerance);
    }

    finish() {
        if (!this.recognized) throw new Error("Not a DC area report.");
        if (this.pending_) throw new Error("Incomplete DC area row.");
        if (!this.root_) throw new Error("DC area report contains no hierarchy rows.");
        return this.tree_.finish();
    }
}

export default class DcAreaDriver {
    load(reader: FileReader, finish: FinishCallback, progress: ProgressCallback, error: ErrorCallback) {
        loadReport(new AreaParser(), reader, finish, progress, error);
    }
    itemNames() { return ["total", "comb", "non-comb", "black-box"]; }
    fileNodeToStr(node: DataNode, root: DataNode, index: number, detailed: boolean) {
        return describeReport(node, root, index, detailed, this.itemNames());
    }
}
